name: Node.js CI

on:
  push:
    branches:
      - 'main'

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.19.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Use Node.js ${{ matrix.node-version }} to build and start app
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    # - run: npm start &

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/node-hello:latest


    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.7.4

    - name: Terraform Init
      run: terraform init 

    - name: Terraform Destroy 
      run: terraform destroy -auto-approve -input=false
      continue-on-error: true

    - name: Remove existing app container
      run: |
        if docker ps -a | grep -q app; then
          echo "Found existing 'app' container. Removing..."
          docker rm -f app
        else
          echo "No 'app' container found."
        fi        

    - name: Terraform Apply
      run: terraform apply -input=false -auto-approve
