name: Node.js CI

on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.19.1]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}    

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.7.4

    - name: Terraform Init
      run: terraform init

    - name: Clean Previous Deployment
      run: terraform destroy -auto-approve -input=false
      env:
        TF_VAR_dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
        TF_VAR_dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}


    - name: Build Docker Image
      run: terraform apply -target=docker_image.app_image -auto-approve -input=false
      env:
        TF_VAR_dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
        TF_VAR_dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}     

    - name: Push to Docker Hub
      run: terraform apply -target=docker_registry_image.app_image -auto-approve -input=false
      env:
        TF_VAR_dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
        TF_VAR_dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}



    - name: Deploy Container
      run: terraform apply -target=docker_container.app_container -auto-approve -input=false
      env:
        TF_VAR_dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
        TF_VAR_dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
